.github/workflows/nbst.yml

diff --git a/.github/workflows/nbst.yml b/.github/workflows/nbst.yml
--- a/.github/workflows/nbst.yml
+++ b/.github/workflows/nbst.yml
@@ -69,47 +69,54 @@ jobs:
           echo "Downloading duckdb-binaries-$name artifact..."
           if gh run download ${{ inputs.run_id }} --repo ${{ env.GH_REPO }} -n duckdb-binaries-$name; then
             echo "Artifact duckdb-binaries-$name is successfuly downloaded."
-            unzip duckdb_cli-${{ inputs.architecture }}.zip
+            # unzip duckdb_cli-${{ inputs.architecture }}.zip
 
-            echo "Verifying version..."
-            full_sha=$(gh run view ${{ inputs.run_id }} --repo ${{ env.GH_REPO }} --json headSha -q .headSha)            
-            if [[ ${{ inputs.architecture }} == linux-aarch64 ]]; then
-              tmp_sha=$(docker run --rm --platform linux/aarch64 -v $(pwd):/duckdb/duckdb ubuntu:22.04 /bin/bash -c './duckdb --version')
-            else
-              tmp_sha=$(./duckdb --version)
-            fi
-            short_sha=$(echo $tmp_sha | awk -F' ' "{ print \$2 }")
-            if [[ "$full_sha" != "$short_sha"* ]]; then
-              printf "- The version of \`${{ inputs.nightly-build }}\` build (\`$short_sha\`) doesn't match to the version triggered the build (\`$full_sha\`).\n " > issue_verify_version_${{ inputs.architecture }}.txt
-              cat issue_verify_version_${{ inputs.architecture }}.txt
-              exit 1
-            fi
-            echo "has_artifact=true" >> $GITHUB_OUTPUT
-          else  
-            echo "Downloading duckdb-binaries-$name artifact is failed."
-            printf "#### No artifacts with name duckdb-binaries-$name provided.\n" > issue_verify_version_${{ inputs.architecture }}.txt
-            cat issue_verify_version_${{ inputs.architecture }}.txt
-            echo "has_artifact=false" >> $GITHUB_OUTPUT
+            echo "Verifying version and test extensions..."
+
+            python scripts/verify_and_test.py duckdb_cli-${{ inputs.architecture }}.zip \
+              --nightly_build ${{ inputs.nightly-build }} --platform ${{ inputs.platform }} \
+              --architecture ${{ inputs.architecture }} \
+              --run_id ${{ inputs.run_id }} --runs_on ${{ inputs.runs-on }} \
+              --config ext/.github/config/out_of_tree_extensions.cmake
+
+          #   full_sha=$(gh run view ${{ inputs.run_id }} --repo ${{ env.GH_REPO }} --json headSha -q .headSha)            
+          #   if [[ ${{ inputs.architecture }} == linux-aarch64 ]]; then
+          #     tmp_sha=$(docker run --rm --platform linux/aarch64 -v $(pwd):/duckdb/duckdb ubuntu:22.04 /bin/bash -c './duckdb --version')
+          #   else
+          #     tmp_sha=$(./duckdb --version)
+          #   fi
+          #   short_sha=$(echo $tmp_sha | awk -F' ' "{ print \$2 }")
+          #   if [[ "$full_sha" != "$short_sha"* ]]; then
+          #     printf "- The version of \`${{ inputs.nightly-build }}\` build (\`$short_sha\`) doesn't match to the version triggered the build (\`$full_sha\`).\n " > issue_verify_version_${{ inputs.architecture }}.txt
+          #     cat issue_verify_version_${{ inputs.architecture }}.txt
+          #     exit 1
+          #   fi
+          #   echo "has_artifact=true" >> $GITHUB_OUTPUT
+          # else  
+          #   echo "Downloading duckdb-binaries-$name artifact is failed."
+          #   printf "#### No artifacts with name duckdb-binaries-$name provided.\n" > issue_verify_version_${{ inputs.architecture }}.txt
+          #   cat issue_verify_version_${{ inputs.architecture }}.txt
+          #   echo "has_artifact=false" >> $GITHUB_OUTPUT
           fi
       # probably remove this
-      - name: Upload issue
-        uses: actions/upload-artifact@v4
-        with:
-          name: issue_verify_version_${{ inputs.architecture }}
-          path: issue_verify_version_${{ inputs.architecture }}.txt
-          if-no-files-found: ignore
+      # - name: Upload issue
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: issue_verify_version_${{ inputs.architecture }}
+      #     path: issue_verify_version_${{ inputs.architecture }}.txt
+      #     if-no-files-found: ignore
 
       
-      - name: Test ${{ inputs.nightly-build }} using Python script
-        shell: bash
-        # if: inputs.architecture == 'linux-aarch64' && steps.verify-build.outputs.has_artifact == 'true'
-        if: steps.verify-build.outputs.has_artifact == 'true'
-        run: |
-          python -m pip show duckdb
-          python scripts/verify_and_test.py \
-            --nightly_build ${{ inputs.nightly-build }} --platform ${{ inputs.platform }} --architecture ${{ inputs.architecture }} \
-            --run_id ${{ inputs.run_id }} --runs_on ${{ inputs.runs-on }} \
-            --config ext/.github/config/out_of_tree_extensions.cmake
+      # - name: Test ${{ inputs.nightly-build }} using Python script
+      #   shell: bash
+      #   # if: inputs.architecture == 'linux-aarch64' && steps.verify-build.outputs.has_artifact == 'true'
+      #   if: steps.verify-build.outputs.has_artifact == 'true'
+      #   run: |
+      #     python -m pip show duckdb
+      #     python scripts/verify_and_test.py \
+      #       --nightly_build ${{ inputs.nightly-build }} --platform ${{ inputs.platform }} --architecture ${{ inputs.architecture }} \
+      #       --run_id ${{ inputs.run_id }} --runs_on ${{ inputs.runs-on }} \
+      #       --config ext/.github/config/out_of_tree_extensions.cmake
 
       #     matches=$(python scripts/find_extensions.py ext/.github/config/out_of_tree_extensions.cmake | tr -d '[],')
 
